# Alembic configuration file

[alembic]
sqlalchemy.url = driver:///username:password@host/dbname
script_location = alembic
prepend_sys_path = .
version_path_separator = :
version_locations = %(here)s/versions

[loggers]
keys = root,sqlalchemy,alembic.environment

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console
qualname =

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic.environment]
level = INFO
handlers =
qualname = alembic.environment

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
